builders:
  finch_builder:
    import: "package:finch_builder/builder.dart"
    builder_factories: ["finchBuilder"]
    build_extensions: {".dart": [".finch.dart"]}
    auto_apply: dependents
    build_to: cache
    required_inputs: [".html", ".css"]
