name: finch_builder
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  analyzer: ^6.3.0
  build: ^2.4.0
  code_builder: ^4.9.0
  finch:
    path: ../finch
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.7
  lints: ^3.0.0
