name: example_app
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.4

dependencies:
  finch:
    path: ../finch
  js: ^0.6.7
  web: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  finch_builder:
    path: ../finch_builder
  lints: ^3.0.0
